import { sequelize } from '../../config/database.js';
import TenantFactory from './Tenant.js';
import RoleFactory from './Role.js';
import UserFactory from './User.js';
import TenantUserFactory from './TenantUser.js';
import LearningTrackFactory from './LearningTrack.js';
import CourseFactory from './Course.js';
import ModuleFactory from './Module.js';
import LessonFactory from './Lesson.js';
import LessonContentFactory from './LessonContent.js';
import EnrollmentFactory from './Enrollment.js';
import LessonProgressFactory from './LessonProgress.js';
import CompetencyFactory from './Competency.js';
import LessonCompetencyFactory from './LessonCompetency.js';
import UserCompetencyScoreFactory from './UserCompetencyScore.js';
import AssessmentFactory from './Assessment.js';
import AssessmentQuestionFactory from './AssessmentQuestion.js';
import AssessmentAttemptFactory from './AssessmentAttempt.js';
import AssessmentAnswerFactory from './AssessmentAnswer.js';
import AssessmentEvaluationFactory from './AssessmentEvaluation.js';
import AISessionFactory from './AISession.js';
import AIMessageFactory from './AIMessage.js';
import PromptTemplateFactory from './PromptTemplate.js';
import AIUsageLogFactory from './AIUsageLog.js';
import KnowledgeSourceFactory from './KnowledgeSource.js';
import KnowledgeDocumentFactory from './KnowledgeDocument.js';
import KnowledgeChunkFactory from './KnowledgeChunk.js';
import IntegrationEventFactory from './IntegrationEvent.js';
import LearnerProfileFactory from './LearnerProfile.js';
import LearningGoalFactory from './LearningGoal.js';
import LearningStyleProfileFactory from './LearningStyleProfile.js';
import JourneyPlanFactory from './JourneyPlan.js';
import JourneyPlanStepFactory from './JourneyPlanStep.js';
import JourneyStateFactory from './JourneyState.js';
import JourneyRewardFactory from './JourneyReward.js';
import JourneyEventFactory from './JourneyEvent.js';
import MentorStateFactory from './MentorState.js';
import JourneyMissionFactory from './JourneyMission.js';
import JourneyTwistRuleFactory from './JourneyTwistRule.js';
import JourneyTwistLogFactory from './JourneyTwistLog.js';
import ScenarioFactory from './Scenario.js';
import ScenarioEpisodeFactory from './ScenarioEpisode.js';
import DecisionOptionFactory from './DecisionOption.js';
import SimulationRunFactory from './SimulationRun.js';
import DecisionLogFactory from './DecisionLog.js';
import CompetencyEvidenceFactory from './CompetencyEvidence.js';
import AssessmentSubmissionFactory from './AssessmentSubmission.js';
import GamificationEventFactory from './GamificationEvent.js';
import UserProgressionFactory from './UserProgression.js';
import UserStreakFactory from './UserStreak.js';
import AchievementFactory from './Achievement.js';
import UserAchievementFactory from './UserAchievement.js';
import RewardRuleFactory from './RewardRule.js';
import LevelRuleFactory from './LevelRule.js';

export const Tenant = TenantFactory(sequelize);
export const Role = RoleFactory(sequelize);
export const User = UserFactory(sequelize);
export const TenantUser = TenantUserFactory(sequelize);
export const LearningTrack = LearningTrackFactory(sequelize);
export const Course = CourseFactory(sequelize);
export const Module = ModuleFactory(sequelize);
export const Lesson = LessonFactory(sequelize);
export const LessonContent = LessonContentFactory(sequelize);
export const Enrollment = EnrollmentFactory(sequelize);
export const LessonProgress = LessonProgressFactory(sequelize);
export const Competency = CompetencyFactory(sequelize);
export const LessonCompetency = LessonCompetencyFactory(sequelize);
export const UserCompetencyScore = UserCompetencyScoreFactory(sequelize);
export const Assessment = AssessmentFactory(sequelize);
export const AssessmentQuestion = AssessmentQuestionFactory(sequelize);
export const AssessmentAttempt = AssessmentAttemptFactory(sequelize);
export const AssessmentAnswer = AssessmentAnswerFactory(sequelize);
export const AssessmentEvaluation = AssessmentEvaluationFactory(sequelize);
export const AISession = AISessionFactory(sequelize);
export const AIMessage = AIMessageFactory(sequelize);
export const PromptTemplate = PromptTemplateFactory(sequelize);
export const AIUsageLog = AIUsageLogFactory(sequelize);
export const KnowledgeSource = KnowledgeSourceFactory(sequelize);
export const KnowledgeDocument = KnowledgeDocumentFactory(sequelize);
export const KnowledgeChunk = KnowledgeChunkFactory(sequelize);
export const IntegrationEvent = IntegrationEventFactory(sequelize);
export const LearnerProfile = LearnerProfileFactory(sequelize);
export const LearningGoal = LearningGoalFactory(sequelize);
export const LearningStyleProfile = LearningStyleProfileFactory(sequelize);
export const JourneyPlan = JourneyPlanFactory(sequelize);
export const JourneyPlanStep = JourneyPlanStepFactory(sequelize);
export const JourneyState = JourneyStateFactory(sequelize);
export const JourneyReward = JourneyRewardFactory(sequelize);
export const JourneyEvent = JourneyEventFactory(sequelize);
export const MentorState = MentorStateFactory(sequelize);
export const JourneyMission = JourneyMissionFactory(sequelize);
export const JourneyTwistRule = JourneyTwistRuleFactory(sequelize);
export const JourneyTwistLog = JourneyTwistLogFactory(sequelize);
export const Scenario = ScenarioFactory(sequelize);
export const ScenarioEpisode = ScenarioEpisodeFactory(sequelize);
export const DecisionOption = DecisionOptionFactory(sequelize);
export const SimulationRun = SimulationRunFactory(sequelize);
export const DecisionLog = DecisionLogFactory(sequelize);
export const CompetencyEvidence = CompetencyEvidenceFactory(sequelize);
export const AssessmentSubmission = AssessmentSubmissionFactory(sequelize);
export const GamificationEvent = GamificationEventFactory(sequelize);
export const UserProgression = UserProgressionFactory(sequelize);
export const UserStreak = UserStreakFactory(sequelize);
export const Achievement = AchievementFactory(sequelize);
export const UserAchievement = UserAchievementFactory(sequelize);
export const RewardRule = RewardRuleFactory(sequelize);
export const LevelRule = LevelRuleFactory(sequelize);

TenantUser.belongsTo(User, { as: 'user', foreignKey: 'userId' });
TenantUser.belongsTo(Tenant, { as: 'tenant', foreignKey: 'tenantId' });
TenantUser.belongsTo(Role, { as: 'role', foreignKey: 'roleId' });
LearningTrack.belongsTo(Tenant, { as: 'tenant', foreignKey: 'tenantId' });
LearningTrack.hasMany(Course, { as: 'courses', foreignKey: 'learningTrackId' });
Course.belongsTo(LearningTrack, { as: 'track', foreignKey: 'learningTrackId' });
Course.hasMany(Module, { as: 'modules', foreignKey: 'courseId' });
Module.belongsTo(Course, { as: 'course', foreignKey: 'courseId' });
Module.hasMany(Lesson, { as: 'lessons', foreignKey: 'moduleId' });
Lesson.belongsTo(Module, { as: 'module', foreignKey: 'moduleId' });
Lesson.hasMany(LessonContent, { as: 'contents', foreignKey: 'lessonId' });
Assessment.belongsTo(Lesson, { as: 'lesson', foreignKey: 'lessonId' });
Assessment.hasMany(AssessmentQuestion, { as: 'questions', foreignKey: 'assessmentId' });
AssessmentAttempt.belongsTo(Assessment, { as: 'assessment', foreignKey: 'assessmentId' });
AssessmentAttempt.hasMany(AssessmentAnswer, { as: 'answers', foreignKey: 'attemptId' });
AssessmentAttempt.hasMany(AssessmentEvaluation, { as: 'evaluations', foreignKey: 'attemptId' });
KnowledgeSource.hasMany(KnowledgeDocument, { as: 'documents', foreignKey: 'knowledgeSourceId' });
KnowledgeDocument.belongsTo(KnowledgeSource, { as: 'source', foreignKey: 'knowledgeSourceId' });
KnowledgeDocument.hasMany(KnowledgeChunk, { as: 'chunks', foreignKey: 'knowledgeDocumentId' });
AISession.hasMany(AIMessage, { as: 'messages', foreignKey: 'aiSessionId' });
User.hasOne(LearnerProfile, { as: 'learnerProfile', foreignKey: 'userId' });
User.hasMany(LearningGoal, { as: 'learningGoals', foreignKey: 'userId' });
User.hasOne(LearningStyleProfile, { as: 'learningStyleProfile', foreignKey: 'userId' });
User.hasMany(JourneyPlan, { as: 'journeyPlans', foreignKey: 'userId' });
User.hasOne(JourneyState, { as: 'journeyState', foreignKey: 'userId' });
User.hasMany(SimulationRun, { as: 'simulationRuns', foreignKey: 'userId' });
User.hasMany(CompetencyEvidence, { as: 'competencyEvidences', foreignKey: 'userId' });
User.hasMany(AssessmentSubmission, { as: 'assessmentSubmissions', foreignKey: 'userId' });
User.hasOne(UserProgression, { as: 'progression', foreignKey: 'userId' });
User.hasOne(UserStreak, { as: 'streak', foreignKey: 'userId' });
User.hasMany(GamificationEvent, { as: 'gamificationEvents', foreignKey: 'userId' });
User.hasMany(UserAchievement, { as: 'unlockedAchievements', foreignKey: 'userId' });

LearningGoal.belongsTo(User, { as: 'user', foreignKey: 'userId' });
LearningStyleProfile.belongsTo(User, { as: 'user', foreignKey: 'userId' });
LearnerProfile.belongsTo(User, { as: 'user', foreignKey: 'userId' });

JourneyPlan.belongsTo(User, { as: 'user', foreignKey: 'userId' });
JourneyPlan.belongsTo(LearningGoal, { as: 'learningGoal', foreignKey: 'learningGoalId' });
JourneyPlan.hasMany(JourneyPlanStep, { as: 'steps', foreignKey: 'journeyPlanId' });
JourneyPlanStep.belongsTo(JourneyPlan, { as: 'journeyPlan', foreignKey: 'journeyPlanId' });
JourneyPlanStep.belongsTo(Competency, { as: 'competency', foreignKey: 'competencyId' });
JourneyPlanStep.belongsTo(Lesson, { as: 'lesson', foreignKey: 'lessonId' });

JourneyState.belongsTo(User, { as: 'user', foreignKey: 'userId' });
JourneyState.belongsTo(JourneyPlan, { as: 'journeyPlan', foreignKey: 'journeyPlanId' });
JourneyState.belongsTo(JourneyPlanStep, { as: 'currentStep', foreignKey: 'currentStepId' });
JourneyState.hasMany(JourneyReward, { as: 'rewards', foreignKey: 'journeyStateId' });
JourneyState.hasMany(JourneyEvent, { as: 'events', foreignKey: 'journeyId' });
JourneyState.hasOne(MentorState, { as: 'mentorState', foreignKey: 'journeyStateId' });

JourneyReward.belongsTo(User, { as: 'user', foreignKey: 'userId' });
JourneyReward.belongsTo(JourneyState, { as: 'journeyState', foreignKey: 'journeyStateId' });

JourneyEvent.belongsTo(User, { as: 'user', foreignKey: 'userId' });
JourneyEvent.belongsTo(JourneyState, { as: 'journeyState', foreignKey: 'journeyId' });

MentorState.belongsTo(User, { as: 'user', foreignKey: 'userId' });
MentorState.belongsTo(JourneyState, { as: 'journeyState', foreignKey: 'journeyStateId' });

JourneyMission.belongsTo(Tenant, { as: 'tenant', foreignKey: 'tenantId' });

JourneyTwistRule.belongsTo(Tenant, { as: 'tenant', foreignKey: 'tenantId' });

JourneyTwistLog.belongsTo(Tenant, { as: 'tenant', foreignKey: 'tenantId' });
JourneyTwistLog.belongsTo(User, { as: 'user', foreignKey: 'userId' });
JourneyTwistLog.belongsTo(JourneyState, { as: 'journeyState', foreignKey: 'journeyStateId' });
JourneyTwistLog.belongsTo(JourneyTwistRule, { as: 'twistRule', foreignKey: 'twistRuleId' });

Scenario.belongsTo(Competency, { as: 'competency', foreignKey: 'competencyId' });
Scenario.belongsTo(LearningTrack, { as: 'track', foreignKey: 'learningTrackId' });
Scenario.belongsTo(Course, { as: 'course', foreignKey: 'courseId' });
Scenario.belongsTo(Lesson, { as: 'lesson', foreignKey: 'lessonId' });
Scenario.hasMany(ScenarioEpisode, { as: 'episodes', foreignKey: 'scenarioId' });

ScenarioEpisode.belongsTo(Scenario, { as: 'scenario', foreignKey: 'scenarioId' });
ScenarioEpisode.hasMany(DecisionOption, { as: 'options', foreignKey: 'scenarioEpisodeId' });
DecisionOption.belongsTo(ScenarioEpisode, { as: 'episode', foreignKey: 'scenarioEpisodeId' });

SimulationRun.belongsTo(User, { as: 'user', foreignKey: 'userId' });
SimulationRun.belongsTo(Scenario, { as: 'scenario', foreignKey: 'scenarioId' });
SimulationRun.belongsTo(JourneyPlan, { as: 'journeyPlan', foreignKey: 'journeyPlanId' });
SimulationRun.hasMany(DecisionLog, { as: 'decisionLogs', foreignKey: 'simulationRunId' });

DecisionLog.belongsTo(SimulationRun, { as: 'simulationRun', foreignKey: 'simulationRunId' });
DecisionLog.belongsTo(ScenarioEpisode, { as: 'episode', foreignKey: 'scenarioEpisodeId' });
DecisionLog.belongsTo(DecisionOption, { as: 'option', foreignKey: 'decisionOptionId' });

CompetencyEvidence.belongsTo(User, { as: 'user', foreignKey: 'userId' });
CompetencyEvidence.belongsTo(Competency, { as: 'competency', foreignKey: 'competencyId' });
AssessmentSubmission.belongsTo(User, { as: 'user', foreignKey: 'userId' });
AssessmentSubmission.belongsTo(Assessment, { as: 'assessment', foreignKey: 'assessmentId' });
AssessmentSubmission.belongsTo(AssessmentAttempt, { as: 'attempt', foreignKey: 'assessmentAttemptId' });

UserProgression.belongsTo(User, { as: 'user', foreignKey: 'userId' });
UserStreak.belongsTo(User, { as: 'user', foreignKey: 'userId' });
GamificationEvent.belongsTo(User, { as: 'user', foreignKey: 'userId' });
GamificationEvent.belongsTo(Tenant, { as: 'tenant', foreignKey: 'tenantId' });

Achievement.belongsTo(Tenant, { as: 'tenant', foreignKey: 'tenantId' });
UserAchievement.belongsTo(User, { as: 'user', foreignKey: 'userId' });
UserAchievement.belongsTo(Achievement, { as: 'achievement', foreignKey: 'achievementId' });

RewardRule.belongsTo(Tenant, { as: 'tenant', foreignKey: 'tenantId' });
LevelRule.belongsTo(Tenant, { as: 'tenant', foreignKey: 'tenantId' });

export { sequelize };
