import { sequelize } from '../../config/database.js';
import TenantFactory from './Tenant.js';
import RoleFactory from './Role.js';
import UserFactory from './User.js';
import TenantUserFactory from './TenantUser.js';
import LearningTrackFactory from './LearningTrack.js';
import CourseFactory from './Course.js';
import ModuleFactory from './Module.js';
import LessonFactory from './Lesson.js';
import LessonContentFactory from './LessonContent.js';
import EnrollmentFactory from './Enrollment.js';
import LessonProgressFactory from './LessonProgress.js';
import CompetencyFactory from './Competency.js';
import LessonCompetencyFactory from './LessonCompetency.js';
import UserCompetencyScoreFactory from './UserCompetencyScore.js';
import AssessmentFactory from './Assessment.js';
import AssessmentQuestionFactory from './AssessmentQuestion.js';
import AssessmentAttemptFactory from './AssessmentAttempt.js';
import AssessmentAnswerFactory from './AssessmentAnswer.js';
import AssessmentEvaluationFactory from './AssessmentEvaluation.js';
import AISessionFactory from './AISession.js';
import AIMessageFactory from './AIMessage.js';
import PromptTemplateFactory from './PromptTemplate.js';
import AIUsageLogFactory from './AIUsageLog.js';
import KnowledgeSourceFactory from './KnowledgeSource.js';
import KnowledgeDocumentFactory from './KnowledgeDocument.js';
import KnowledgeChunkFactory from './KnowledgeChunk.js';
import IntegrationEventFactory from './IntegrationEvent.js';

export const Tenant = TenantFactory(sequelize);
export const Role = RoleFactory(sequelize);
export const User = UserFactory(sequelize);
export const TenantUser = TenantUserFactory(sequelize);
export const LearningTrack = LearningTrackFactory(sequelize);
export const Course = CourseFactory(sequelize);
export const Module = ModuleFactory(sequelize);
export const Lesson = LessonFactory(sequelize);
export const LessonContent = LessonContentFactory(sequelize);
export const Enrollment = EnrollmentFactory(sequelize);
export const LessonProgress = LessonProgressFactory(sequelize);
export const Competency = CompetencyFactory(sequelize);
export const LessonCompetency = LessonCompetencyFactory(sequelize);
export const UserCompetencyScore = UserCompetencyScoreFactory(sequelize);
export const Assessment = AssessmentFactory(sequelize);
export const AssessmentQuestion = AssessmentQuestionFactory(sequelize);
export const AssessmentAttempt = AssessmentAttemptFactory(sequelize);
export const AssessmentAnswer = AssessmentAnswerFactory(sequelize);
export const AssessmentEvaluation = AssessmentEvaluationFactory(sequelize);
export const AISession = AISessionFactory(sequelize);
export const AIMessage = AIMessageFactory(sequelize);
export const PromptTemplate = PromptTemplateFactory(sequelize);
export const AIUsageLog = AIUsageLogFactory(sequelize);
export const KnowledgeSource = KnowledgeSourceFactory(sequelize);
export const KnowledgeDocument = KnowledgeDocumentFactory(sequelize);
export const KnowledgeChunk = KnowledgeChunkFactory(sequelize);
export const IntegrationEvent = IntegrationEventFactory(sequelize);

TenantUser.belongsTo(User, { as: 'user', foreignKey: 'userId' });
TenantUser.belongsTo(Tenant, { as: 'tenant', foreignKey: 'tenantId' });
TenantUser.belongsTo(Role, { as: 'role', foreignKey: 'roleId' });
LearningTrack.belongsTo(Tenant, { as: 'tenant', foreignKey: 'tenantId' });
LearningTrack.hasMany(Course, { as: 'courses', foreignKey: 'learningTrackId' });
Course.belongsTo(LearningTrack, { as: 'track', foreignKey: 'learningTrackId' });
Course.hasMany(Module, { as: 'modules', foreignKey: 'courseId' });
Module.belongsTo(Course, { as: 'course', foreignKey: 'courseId' });
Module.hasMany(Lesson, { as: 'lessons', foreignKey: 'moduleId' });
Lesson.belongsTo(Module, { as: 'module', foreignKey: 'moduleId' });
Lesson.hasMany(LessonContent, { as: 'contents', foreignKey: 'lessonId' });
Assessment.belongsTo(Lesson, { as: 'lesson', foreignKey: 'lessonId' });
Assessment.hasMany(AssessmentQuestion, { as: 'questions', foreignKey: 'assessmentId' });
AssessmentAttempt.belongsTo(Assessment, { as: 'assessment', foreignKey: 'assessmentId' });
AssessmentAttempt.hasMany(AssessmentAnswer, { as: 'answers', foreignKey: 'attemptId' });
AssessmentAttempt.hasMany(AssessmentEvaluation, { as: 'evaluations', foreignKey: 'attemptId' });
KnowledgeSource.hasMany(KnowledgeDocument, { as: 'documents', foreignKey: 'knowledgeSourceId' });
KnowledgeDocument.belongsTo(KnowledgeSource, { as: 'source', foreignKey: 'knowledgeSourceId' });
KnowledgeDocument.hasMany(KnowledgeChunk, { as: 'chunks', foreignKey: 'knowledgeDocumentId' });
AISession.hasMany(AIMessage, { as: 'messages', foreignKey: 'aiSessionId' });

export { sequelize };
