import systemRoutes from './system/system.routes.js';
import authRoutes from './auth/auth.routes.js';
import learningRoutes from './learning/learning.routes.js';
import assessmentRoutes from './assessment/assessment.routes.js';
import competencyRoutes from './competency/competency.routes.js';
import aiRoutes from './ai/ai.routes.js';
import knowledgeRoutes from './knowledge/knowledge.routes.js';
import integrationRoutes from './integration/integration.routes.js';
import profileRoutes from './profile/profile.routes.js';
import journeyRoutes from './journey/journey.routes.js';
import simulationRoutes from './simulation/simulation.routes.js';
import mentorRoutes from './mentor/mentor.routes.js';
import analyticsRoutes from './analytics/analytics.routes.js';
import feedbackRoutes from './feedback/feedback.routes.js';
import journeyFlowRoutes from './journey-flow/journey-flow.routes.js';
import gamificationRoutes from './gamification/gamification.routes.js';
import journeyEngineRoutes from './journey-engine/journey-engine.routes.js';
import journeyAdaptiveRoutes from './journey-adaptive/journey-adaptive.routes.js';

export function registerModules(app) {
  app.use(systemRoutes);
  app.use('/auth', authRoutes);
  app.use('/api/auth', authRoutes);
  app.use('/api', learningRoutes);
  app.use('/api', assessmentRoutes);
  app.use('/api', competencyRoutes);
  app.use('/api', aiRoutes);
  app.use('/api', knowledgeRoutes);
  app.use('/api', integrationRoutes);
  app.use('/api', profileRoutes);
  app.use('/api', journeyRoutes);
  app.use('/api', simulationRoutes);
  app.use('/api', mentorRoutes);
  app.use('/api', analyticsRoutes);
  app.use('/api', feedbackRoutes);
  app.use('/api', journeyFlowRoutes);
  app.use('/api', journeyEngineRoutes);
  app.use('/api', gamificationRoutes);
  app.use('/api', journeyAdaptiveRoutes);
}
